FROM node:14-slim

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt-get update
RUN apt-get install -y wget gnupg
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update
RUN apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 --no-install-recommends

# Dev only, to add the "ps" command:
RUN apt-get install -y procps

# Temporary patch to install a node module from github
RUN apt-get install -y git

RUN rm -rf /var/lib/apt/lists/*

# Ensure node_modules belongs to node user
WORKDIR /app
RUN mkdir -p /app/node_modules ; chown -R node:node /app/node_modules
# RUN mkdir -p /plugin/components ; chown -R node:node /plugin/components # KO on mounted volume
# More answers here: https://stackoverflow.com/questions/40462189/docker-compose-set-user-and-group-on-mounted-volume

# USER node
