FROM node:16-alpine

RUN apk -U upgrade && apk add git

# Ensure node_modules belongs to node user
WORKDIR /app
RUN mkdir -p /app/node_modules ; chown -R node:node /app/node_modules
# RUN mkdir -p /plugin/components ; chown -R node:node /plugin/components # KO on mounted volume
# More answers here: https://stackoverflow.com/questions/40462189/docker-compose-set-user-and-group-on-mounted-volume

# USER node
