/* eslint-disable */

import { SceneNodeNoMethod } from '../sb-serialize-preview/sb-serialize.model';

export const devFigmaConfig = {
  id: '3857:401321',
  type: 'FRAME',
  name: 'Container',
  visible: true,
  opacity: 1,
  blendMode: 'PASS_THROUGH',
  isMask: false,
  effects: [],
  effectStyleId: '',
  x: 80,
  y: 96,
  width: 1280,
  height: 312,
  rotation: 0,
  layoutAlign: 'INHERIT',
  layoutGrow: 0,
  exportSettings: [],
  fills: [],
  fillStyleId: '',
  strokes: [],
  strokeStyleId: '',
  strokeWeight: 1,
  strokeAlign: 'INSIDE',
  strokeJoin: 'MITER',
  dashPattern: [],
  strokeCap: 'NONE',
  strokeMiterLimit: 4,
  cornerSmoothing: 0,
  topLeftRadius: 0,
  topRightRadius: 0,
  bottomLeftRadius: 0,
  bottomRightRadius: 0,
  paddingLeft: 32,
  paddingRight: 32,
  paddingTop: 0,
  paddingBottom: 0,
  primaryAxisAlignItems: 'MIN',
  counterAxisAlignItems: 'CENTER',
  primaryAxisSizingMode: 'AUTO',
  layoutGrids: [],
  gridStyleId: '',
  clipsContent: false,
  constraints: { horizontal: 'MIN', vertical: 'MIN' },
  layoutMode: 'VERTICAL',
  counterAxisSizingMode: 'FIXED',
  itemSpacing: 32,
  overflowDirection: 'NONE',
  overlayPositionType: 'CENTER',
  overlayBackground: { type: 'NONE' },
  overlayBackgroundInteraction: 'NONE',
  reactions: [],
  children: [
    {
      id: '3857:401322',
      type: 'FRAME',
      name: 'Content',
      visible: true,
      opacity: 1,
      blendMode: 'PASS_THROUGH',
      isMask: false,
      effects: [],
      effectStyleId: '',
      x: 32,
      y: 0,
      width: 1216,
      height: 312,
      rotation: 0,
      layoutAlign: 'STRETCH',
      layoutGrow: 0,
      exportSettings: [],
      fills: [],
      fillStyleId: '',
      strokes: [],
      strokeStyleId: '',
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      strokeJoin: 'MITER',
      dashPattern: [],
      strokeCap: 'NONE',
      strokeMiterLimit: 4,
      cornerSmoothing: 0,
      topLeftRadius: 0,
      topRightRadius: 0,
      bottomLeftRadius: 0,
      bottomRightRadius: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
      primaryAxisAlignItems: 'MIN',
      counterAxisAlignItems: 'CENTER',
      primaryAxisSizingMode: 'AUTO',
      layoutGrids: [],
      gridStyleId: '',
      clipsContent: false,
      constraints: { horizontal: 'MIN', vertical: 'MIN' },
      layoutMode: 'VERTICAL',
      counterAxisSizingMode: 'FIXED',
      itemSpacing: 48,
      overflowDirection: 'NONE',
      overlayPositionType: 'CENTER',
      overlayBackground: { type: 'NONE' },
      overlayBackgroundInteraction: 'NONE',
      reactions: [],
      children: [
        {
          id: '3857:401323',
          type: 'FRAME',
          name: 'Heading and supporting text',
          visible: true,
          opacity: 1,
          blendMode: 'PASS_THROUGH',
          isMask: false,
          effects: [],
          effectStyleId: '',
          x: 96,
          y: 0,
          width: 1024,
          height: 204,
          rotation: 0,
          layoutAlign: 'INHERIT',
          layoutGrow: 0,
          exportSettings: [],
          fills: [],
          fillStyleId: '',
          strokes: [],
          strokeStyleId: '',
          strokeWeight: 1,
          strokeAlign: 'INSIDE',
          strokeJoin: 'MITER',
          dashPattern: [],
          strokeCap: 'NONE',
          strokeMiterLimit: 4,
          cornerSmoothing: 0,
          topLeftRadius: 0,
          topRightRadius: 0,
          bottomLeftRadius: 0,
          bottomRightRadius: 0,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
          primaryAxisAlignItems: 'MIN',
          counterAxisAlignItems: 'CENTER',
          primaryAxisSizingMode: 'AUTO',
          layoutGrids: [],
          gridStyleId: '',
          clipsContent: false,
          constraints: { horizontal: 'MIN', vertical: 'MIN' },
          layoutMode: 'VERTICAL',
          counterAxisSizingMode: 'FIXED',
          itemSpacing: 24,
          overflowDirection: 'NONE',
          overlayPositionType: 'CENTER',
          overlayBackground: { type: 'NONE' },
          overlayBackgroundInteraction: 'NONE',
          reactions: [],
          children: [
            {
              id: '3857:401324',
              type: 'FRAME',
              name: 'Heading and badge',
              visible: true,
              opacity: 1,
              blendMode: 'PASS_THROUGH',
              isMask: false,
              effects: [],
              effectStyleId: '',
              x: 0,
              y: 0,
              width: 1024,
              height: 120,
              rotation: 0,
              layoutAlign: 'STRETCH',
              layoutGrow: 0,
              exportSettings: [],
              fills: [],
              fillStyleId: '',
              strokes: [],
              strokeStyleId: '',
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              strokeJoin: 'MITER',
              dashPattern: [],
              strokeCap: 'NONE',
              strokeMiterLimit: 4,
              cornerSmoothing: 0,
              topLeftRadius: 0,
              topRightRadius: 0,
              bottomLeftRadius: 0,
              bottomRightRadius: 0,
              paddingLeft: 0,
              paddingRight: 0,
              paddingTop: 0,
              paddingBottom: 0,
              primaryAxisAlignItems: 'MIN',
              counterAxisAlignItems: 'CENTER',
              primaryAxisSizingMode: 'AUTO',
              layoutGrids: [],
              gridStyleId: '',
              clipsContent: false,
              constraints: { horizontal: 'MIN', vertical: 'MIN' },
              layoutMode: 'VERTICAL',
              counterAxisSizingMode: 'FIXED',
              itemSpacing: 16,
              overflowDirection: 'NONE',
              overlayPositionType: 'CENTER',
              overlayBackground: { type: 'NONE' },
              overlayBackgroundInteraction: 'NONE',
              reactions: [],
              children: [
                {
                  id: '3857:401325',
                  type: 'INSTANCE',
                  name: 'Badge group',
                  visible: true,
                  opacity: 1,
                  blendMode: 'MULTIPLY',
                  isMask: false,
                  effects: [],
                  effectStyleId: '',
                  x: 334.5,
                  y: 0,
                  width: 355,
                  height: 32,
                  rotation: 0,
                  layoutAlign: 'INHERIT',
                  layoutGrow: 0,
                  exportSettings: [],
                  fills: [
                    {
                      type: 'SOLID',
                      visible: true,
                      opacity: 1,
                      blendMode: 'NORMAL',
                      color: { r: 0.9764705896377563, g: 0.9607843160629272, b: 1 },
                    },
                  ],
                  fillStyleId: 'S:df82cbd2126f8d78b6b4fcad4430f7d55e8371ad,',
                  strokes: [],
                  strokeStyleId: '',
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  strokeJoin: 'MITER',
                  dashPattern: [],
                  strokeCap: 'NONE',
                  strokeMiterLimit: 4,
                  cornerSmoothing: 0,
                  topLeftRadius: 16,
                  topRightRadius: 16,
                  bottomLeftRadius: 16,
                  bottomRightRadius: 16,
                  paddingLeft: 4,
                  paddingRight: 10,
                  paddingTop: 4,
                  paddingBottom: 4,
                  primaryAxisAlignItems: 'MIN',
                  counterAxisAlignItems: 'CENTER',
                  primaryAxisSizingMode: 'AUTO',
                  layoutGrids: [],
                  gridStyleId: '',
                  clipsContent: false,
                  constraints: { horizontal: 'MIN', vertical: 'MIN' },
                  layoutMode: 'HORIZONTAL',
                  counterAxisSizingMode: 'AUTO',
                  itemSpacing: 12,
                  overflowDirection: 'NONE',
                  overlayPositionType: 'CENTER',
                  overlayBackground: { type: 'NONE' },
                  overlayBackgroundInteraction: 'NONE',
                  scaleFactor: 1,
                  reactions: [],
                  variantProperties: { Badge: 'Leading', Icon: 'True', Size: 'lg', Color: 'Primary', Theme: 'Light' },
                  children: [
                    {
                      id: 'I3857:401325;1046:9111',
                      type: 'INSTANCE',
                      name: 'Badge',
                      visible: true,
                      opacity: 1,
                      blendMode: 'NORMAL',
                      isMask: false,
                      effects: [],
                      effectStyleId: '',
                      x: 4,
                      y: 4,
                      width: 102,
                      height: 24,
                      rotation: 0,
                      layoutAlign: 'INHERIT',
                      layoutGrow: 0,
                      exportSettings: [],
                      fills: [
                        { type: 'SOLID', visible: false, opacity: 1, blendMode: 'NORMAL', color: { r: 1, g: 1, b: 1 } },
                      ],
                      fillStyleId: '',
                      strokes: [],
                      strokeStyleId: '',
                      strokeWeight: 1,
                      strokeAlign: 'INSIDE',
                      strokeJoin: 'MITER',
                      dashPattern: [],
                      strokeCap: 'NONE',
                      strokeMiterLimit: 4,
                      cornerSmoothing: 0,
                      topLeftRadius: 0,
                      topRightRadius: 0,
                      bottomLeftRadius: 0,
                      bottomRightRadius: 0,
                      paddingLeft: 0,
                      paddingRight: 0,
                      paddingTop: 0,
                      paddingBottom: 0,
                      primaryAxisAlignItems: 'MIN',
                      counterAxisAlignItems: 'MIN',
                      primaryAxisSizingMode: 'AUTO',
                      layoutGrids: [],
                      gridStyleId: '',
                      clipsContent: false,
                      constraints: { horizontal: 'MIN', vertical: 'MIN' },
                      layoutMode: 'HORIZONTAL',
                      counterAxisSizingMode: 'AUTO',
                      itemSpacing: 13,
                      overflowDirection: 'NONE',
                      overlayPositionType: 'CENTER',
                      overlayBackground: { type: 'NONE' },
                      overlayBackgroundInteraction: 'NONE',
                      scaleFactor: 1,
                      reactions: [],
                      variantProperties: { Size: 'md', Icon: 'False', Color: 'Primary' },
                      children: [
                        {
                          id: 'I3857:401325;1046:9111;1046:3821',
                          type: 'INSTANCE',
                          name: '_Badge base',
                          visible: true,
                          opacity: 1,
                          blendMode: 'PASS_THROUGH',
                          isMask: false,
                          effects: [],
                          effectStyleId: '',
                          x: 0,
                          y: 0,
                          width: 102,
                          height: 24,
                          rotation: 0,
                          layoutAlign: 'INHERIT',
                          layoutGrow: 0,
                          exportSettings: [],
                          fills: [
                            {
                              type: 'SOLID',
                              visible: true,
                              opacity: 1,
                              blendMode: 'NORMAL',
                              color: { r: 1, g: 1, b: 1 },
                            },
                          ],
                          fillStyleId: 'S:b89f91551fec70712aa14cf0d408f2e9bb40dfec,',
                          strokes: [],
                          strokeStyleId: '',
                          strokeWeight: 1,
                          strokeAlign: 'INSIDE',
                          strokeJoin: 'MITER',
                          dashPattern: [],
                          strokeCap: 'NONE',
                          strokeMiterLimit: 4,
                          cornerSmoothing: 0,
                          topLeftRadius: 16,
                          topRightRadius: 16,
                          bottomLeftRadius: 16,
                          bottomRightRadius: 16,
                          paddingLeft: 10,
                          paddingRight: 10,
                          paddingTop: 2,
                          paddingBottom: 2,
                          primaryAxisAlignItems: 'CENTER',
                          counterAxisAlignItems: 'CENTER',
                          primaryAxisSizingMode: 'AUTO',
                          layoutGrids: [],
                          gridStyleId: '',
                          clipsContent: false,
                          constraints: { horizontal: 'SCALE', vertical: 'SCALE' },
                          layoutMode: 'HORIZONTAL',
                          counterAxisSizingMode: 'AUTO',
                          itemSpacing: 0,
                          overflowDirection: 'NONE',
                          overlayPositionType: 'CENTER',
                          overlayBackground: { type: 'NONE' },
                          overlayBackgroundInteraction: 'NONE',
                          scaleFactor: 1,
                          reactions: [],
                          variantProperties: { Icon: 'False' },
                          children: [
                            {
                              id: 'I3857:401325;1046:9111;1046:3821;1046:26',
                              type: 'TEXT',
                              listSpacing: 0,
                              name: 'Text',
                              visible: true,
                              opacity: 1,
                              blendMode: 'PASS_THROUGH',
                              isMask: false,
                              effects: [],
                              effectStyleId: '',
                              strokes: [],
                              strokeStyleId: '',
                              strokeWeight: 1,
                              strokeAlign: 'OUTSIDE',
                              strokeJoin: 'MITER',
                              dashPattern: [],
                              strokeCap: 'NONE',
                              strokeMiterLimit: 4,
                              x: 10,
                              y: 2,
                              width: 82,
                              height: 20,
                              rotation: 0,
                              layoutAlign: 'INHERIT',
                              layoutGrow: 0,
                              exportSettings: [],
                              constraints: { horizontal: 'MIN', vertical: 'MIN' },
                              hasMissingFont: false,
                              paragraphIndent: 0,
                              paragraphSpacing: 14,
                              canUpgradeToNativeBidiSupport: false,
                              autoRename: false,
                              textAlignHorizontal: 'CENTER',
                              textAlignVertical: 'TOP',
                              textAutoResize: 'WIDTH_AND_HEIGHT',
                              reactions: [],
                              _textSegments: [
                                {
                                  characters: 'New feature',
                                  start: 0,
                                  end: 11,
                                  fontSize: 14,
                                  fontName: { family: 'Inter', style: 'Medium' },
                                  textDecoration: 'NONE',
                                  textCase: 'ORIGINAL',
                                  lineHeight: { unit: 'PIXELS', value: 20 },
                                  letterSpacing: { unit: 'PERCENT', value: 0 },
                                  fills: [
                                    {
                                      type: 'SOLID',
                                      visible: true,
                                      opacity: 1,
                                      blendMode: 'NORMAL',
                                      color: { r: 0.41150015592575073, g: 0.2541569471359253, b: 0.7772156000137329 },
                                    },
                                  ],
                                  textStyleId: 'S:192fc83f4c84a4752448f462b0911d59dc8d3a48,',
                                  fillStyleId: 'S:273eff8fe592858bf8c9e8de555cf1d52587d2de,',
                                  listOptions: { type: 'NONE' },
                                  indentation: 0,
                                  hyperlink: null,
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: 'I3857:401325;1046:9112',
                      type: 'FRAME',
                      name: 'Content',
                      visible: true,
                      opacity: 1,
                      blendMode: 'PASS_THROUGH',
                      isMask: false,
                      effects: [],
                      effectStyleId: '',
                      x: 118,
                      y: 6,
                      width: 227,
                      height: 20,
                      rotation: 0,
                      layoutAlign: 'INHERIT',
                      layoutGrow: 0,
                      exportSettings: [],
                      fills: [],
                      fillStyleId: '',
                      strokes: [],
                      strokeStyleId: '',
                      strokeWeight: 1,
                      strokeAlign: 'INSIDE',
                      strokeJoin: 'MITER',
                      dashPattern: [],
                      strokeCap: 'NONE',
                      strokeMiterLimit: 4,
                      cornerSmoothing: 0,
                      topLeftRadius: 0,
                      topRightRadius: 0,
                      bottomLeftRadius: 0,
                      bottomRightRadius: 0,
                      paddingLeft: 0,
                      paddingRight: 0,
                      paddingTop: 0,
                      paddingBottom: 0,
                      primaryAxisAlignItems: 'MIN',
                      counterAxisAlignItems: 'CENTER',
                      primaryAxisSizingMode: 'AUTO',
                      layoutGrids: [],
                      gridStyleId: '',
                      clipsContent: false,
                      constraints: { horizontal: 'MIN', vertical: 'MIN' },
                      layoutMode: 'HORIZONTAL',
                      counterAxisSizingMode: 'AUTO',
                      itemSpacing: 4,
                      overflowDirection: 'NONE',
                      overlayPositionType: 'CENTER',
                      overlayBackground: { type: 'NONE' },
                      overlayBackgroundInteraction: 'NONE',
                      reactions: [],
                      children: [
                        {
                          id: 'I3857:401325;1046:9113',
                          type: 'TEXT',
                          listSpacing: 0,
                          name: 'Message',
                          visible: true,
                          opacity: 1,
                          blendMode: 'PASS_THROUGH',
                          isMask: false,
                          effects: [],
                          effectStyleId: '',
                          strokes: [],
                          strokeStyleId: '',
                          strokeWeight: 1,
                          strokeAlign: 'OUTSIDE',
                          strokeJoin: 'MITER',
                          dashPattern: [],
                          strokeCap: 'NONE',
                          strokeMiterLimit: 4,
                          x: 0,
                          y: 0,
                          width: 207,
                          height: 20,
                          rotation: 0,
                          layoutAlign: 'INHERIT',
                          layoutGrow: 0,
                          exportSettings: [],
                          constraints: { horizontal: 'MIN', vertical: 'MIN' },
                          hasMissingFont: false,
                          paragraphIndent: 0,
                          paragraphSpacing: 14,
                          canUpgradeToNativeBidiSupport: true,
                          autoRename: false,
                          textAlignHorizontal: 'LEFT',
                          textAlignVertical: 'TOP',
                          textAutoResize: 'WIDTH_AND_HEIGHT',
                          reactions: [],
                          _textSegments: [
                            {
                              characters: 'Check out the team dashboard',
                              start: 0,
                              end: 28,
                              fontSize: 14,
                              fontName: { family: 'Inter', style: 'Medium' },
                              textDecoration: 'NONE',
                              textCase: 'ORIGINAL',
                              lineHeight: { unit: 'PIXELS', value: 20 },
                              letterSpacing: { unit: 'PERCENT', value: 0 },
                              fills: [
                                {
                                  type: 'SOLID',
                                  visible: true,
                                  opacity: 1,
                                  blendMode: 'NORMAL',
                                  color: { r: 0.41150015592575073, g: 0.2541569471359253, b: 0.7772156000137329 },
                                },
                              ],
                              textStyleId: 'S:192fc83f4c84a4752448f462b0911d59dc8d3a48,',
                              fillStyleId: 'S:273eff8fe592858bf8c9e8de555cf1d52587d2de,',
                              listOptions: { type: 'NONE' },
                              indentation: 0,
                              hyperlink: null,
                            },
                          ],
                        },
                        {
                          id: 'I3857:401325;1046:9278',
                          type: 'INSTANCE',
                          name: 'arrow-right',
                          visible: true,
                          opacity: 1,
                          blendMode: 'PASS_THROUGH',
                          isMask: false,
                          effects: [],
                          effectStyleId: '',
                          x: 211,
                          y: 2,
                          width: 16,
                          height: 16,
                          rotation: 0,
                          layoutAlign: 'INHERIT',
                          layoutGrow: 0,
                          exportSettings: [],
                          fills: [
                            {
                              type: 'SOLID',
                              visible: false,
                              opacity: 1,
                              blendMode: 'NORMAL',
                              color: { r: 1, g: 1, b: 1 },
                            },
                          ],
                          fillStyleId: '',
                          strokes: [],
                          strokeStyleId: '',
                          strokeWeight: 1,
                          strokeAlign: 'INSIDE',
                          strokeJoin: 'MITER',
                          dashPattern: [],
                          strokeCap: 'NONE',
                          strokeMiterLimit: 4,
                          cornerSmoothing: 0,
                          topLeftRadius: 0,
                          topRightRadius: 0,
                          bottomLeftRadius: 0,
                          bottomRightRadius: 0,
                          paddingLeft: 0,
                          paddingRight: 0,
                          paddingTop: 0,
                          paddingBottom: 0,
                          primaryAxisAlignItems: 'MIN',
                          counterAxisAlignItems: 'MIN',
                          primaryAxisSizingMode: 'AUTO',
                          layoutGrids: [],
                          gridStyleId: '',
                          clipsContent: true,
                          constraints: { horizontal: 'MIN', vertical: 'MIN' },
                          layoutMode: 'NONE',
                          counterAxisSizingMode: 'FIXED',
                          itemSpacing: 0,
                          overflowDirection: 'NONE',
                          overlayPositionType: 'CENTER',
                          overlayBackground: { type: 'NONE' },
                          overlayBackgroundInteraction: 'NONE',
                          scaleFactor: 1,
                          reactions: [],
                          variantProperties: null,
                          children: [
                            {
                              id: 'I3857:401325;1046:9278;1037:33952',
                              type: 'VECTOR',
                              name: 'Icon',
                              visible: true,
                              opacity: 1,
                              blendMode: 'PASS_THROUGH',
                              isMask: false,
                              effects: [],
                              effectStyleId: '',
                              fills: [],
                              fillStyleId: '',
                              strokes: [
                                {
                                  type: 'SOLID',
                                  visible: true,
                                  opacity: 1,
                                  blendMode: 'NORMAL',
                                  color: { r: 0.6191517114639282, g: 0.4655293822288513, b: 0.9305490851402283 },
                                },
                              ],
                              strokeStyleId: 'S:36967559694e92e90a05c6889210d3b9576dc79c,',
                              strokeWeight: 1.333299994468689,
                              strokeAlign: 'CENTER',
                              strokeJoin: 'ROUND',
                              dashPattern: [],
                              strokeCap: 'ROUND',
                              strokeMiterLimit: 4,
                              x: 3.3333332538604736,
                              y: 3.3333332538604736,
                              width: 9.333333969116211,
                              height: 9.333333969116211,
                              rotation: 0,
                              layoutAlign: 'INHERIT',
                              layoutGrow: 0,
                              exportSettings: [],
                              constraints: { horizontal: 'SCALE', vertical: 'SCALE' },
                              cornerSmoothing: 0,
                              handleMirroring: 'NONE',
                              reactions: [],
                              _svg: '<svg width="11" height="12" viewBox="0 0 11 12" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M0.833336 6.00016H10.1667M10.1667 6.00016L5.5 1.3335M10.1667 6.00016L5.5 10.6668" stroke="#9E77ED" stroke-width="1.3333" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n',
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: '3857:401326',
                  type: 'TEXT',
                  listSpacing: 0,
                  name: 'Heading',
                  visible: true,
                  opacity: 1,
                  blendMode: 'PASS_THROUGH',
                  isMask: false,
                  effects: [],
                  effectStyleId: '',
                  strokes: [],
                  strokeStyleId: '',
                  strokeWeight: 1,
                  strokeAlign: 'OUTSIDE',
                  strokeJoin: 'MITER',
                  dashPattern: [],
                  strokeCap: 'NONE',
                  strokeMiterLimit: 4,
                  x: 0,
                  y: 48,
                  width: 1024,
                  height: 72,
                  rotation: 0,
                  layoutAlign: 'STRETCH',
                  layoutGrow: 0,
                  exportSettings: [],
                  constraints: { horizontal: 'MIN', vertical: 'MIN' },
                  hasMissingFont: false,
                  paragraphIndent: 0,
                  paragraphSpacing: 60,
                  canUpgradeToNativeBidiSupport: false,
                  autoRename: false,
                  textAlignHorizontal: 'CENTER',
                  textAlignVertical: 'TOP',
                  textAutoResize: 'HEIGHT',
                  reactions: [],
                  _textSegments: [
                    {
                      characters: 'Beautiful analytics to grow smarter',
                      start: 0,
                      end: 35,
                      fontSize: 60,
                      fontName: { family: 'Inter', style: 'Semi Bold' },
                      textDecoration: 'NONE',
                      textCase: 'ORIGINAL',
                      lineHeight: { unit: 'PIXELS', value: 72 },
                      letterSpacing: { unit: 'PERCENT', value: -2 },
                      fills: [
                        {
                          type: 'SOLID',
                          visible: true,
                          opacity: 1,
                          blendMode: 'NORMAL',
                          color: { r: 0.06258822977542877, g: 0.09263458847999573, b: 0.15701963007450104 },
                        },
                      ],
                      textStyleId: 'S:b190222ee87ef5eacb85b5782a953ab8721a8c56,',
                      fillStyleId: 'S:2e3e40309020c62c89de85aa63921ffbf4dfd73c,',
                      listOptions: { type: 'NONE' },
                      indentation: 0,
                      hyperlink: null,
                    },
                  ],
                },
              ],
            },
            {
              id: '3857:401327',
              type: 'TEXT',
              listSpacing: 0,
              name: 'Supporting text',
              visible: true,
              opacity: 1,
              blendMode: 'PASS_THROUGH',
              isMask: false,
              effects: [],
              effectStyleId: '',
              strokes: [],
              strokeStyleId: '',
              strokeWeight: 0,
              strokeAlign: 'INSIDE',
              strokeJoin: 'MITER',
              dashPattern: [],
              strokeCap: 'NONE',
              strokeMiterLimit: 4,
              x: 128,
              y: 144,
              width: 768,
              height: 60,
              rotation: 0,
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              exportSettings: [],
              constraints: { horizontal: 'MIN', vertical: 'MIN' },
              hasMissingFont: false,
              paragraphIndent: 0,
              paragraphSpacing: 20,
              canUpgradeToNativeBidiSupport: false,
              autoRename: false,
              textAlignHorizontal: 'CENTER',
              textAlignVertical: 'TOP',
              textAutoResize: 'HEIGHT',
              reactions: [],
              _textSegments: [
                {
                  characters:
                    'Powerful, self-serve product and growth analytics to help you convert, engage, and retain more users. Trusted by over 4,000 startups.',
                  start: 0,
                  end: 133,
                  fontSize: 20,
                  fontName: { family: 'Inter', style: 'Regular' },
                  textDecoration: 'NONE',
                  textCase: 'ORIGINAL',
                  lineHeight: { unit: 'PIXELS', value: 30 },
                  letterSpacing: { unit: 'PERCENT', value: 0 },
                  fills: [
                    {
                      type: 'SOLID',
                      visible: true,
                      opacity: 1,
                      blendMode: 'NORMAL',
                      color: { r: 0.400882363319397, g: 0.4408170282840729, b: 0.5206862688064575 },
                    },
                  ],
                  textStyleId: 'S:a649260cc23db242d3f4f97f860bfdd4a5c7a55b,',
                  fillStyleId: 'S:f9554079326464271fee6b96f62a83d5a1ee3507,',
                  listOptions: { type: 'NONE' },
                  indentation: 0,
                  hyperlink: null,
                },
              ],
            },
          ],
        },
        {
          id: '3857:401328',
          type: 'FRAME',
          name: 'Actions',
          visible: true,
          opacity: 1,
          blendMode: 'PASS_THROUGH',
          isMask: false,
          effects: [],
          effectStyleId: '',
          x: 417.5,
          y: 252,
          width: 381,
          height: 60,
          rotation: 0,
          layoutAlign: 'INHERIT',
          layoutGrow: 0,
          exportSettings: [],
          fills: [],
          fillStyleId: '',
          strokes: [],
          strokeStyleId: '',
          strokeWeight: 1,
          strokeAlign: 'INSIDE',
          strokeJoin: 'MITER',
          dashPattern: [],
          strokeCap: 'NONE',
          strokeMiterLimit: 4,
          cornerSmoothing: 0,
          topLeftRadius: 0,
          topRightRadius: 0,
          bottomLeftRadius: 0,
          bottomRightRadius: 0,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
          primaryAxisAlignItems: 'MIN',
          counterAxisAlignItems: 'MIN',
          primaryAxisSizingMode: 'AUTO',
          layoutGrids: [],
          gridStyleId: '',
          clipsContent: false,
          constraints: { horizontal: 'MIN', vertical: 'MIN' },
          layoutMode: 'HORIZONTAL',
          counterAxisSizingMode: 'AUTO',
          itemSpacing: 12,
          overflowDirection: 'NONE',
          overlayPositionType: 'CENTER',
          overlayBackground: { type: 'NONE' },
          overlayBackgroundInteraction: 'NONE',
          reactions: [],
          children: [
            {
              id: '3857:401329',
              type: 'INSTANCE',
              name: 'Button',
              visible: true,
              opacity: 1,
              blendMode: 'PASS_THROUGH',
              isMask: false,
              effects: [],
              effectStyleId: '',
              x: 0,
              y: 0,
              width: 143,
              height: 60,
              rotation: 0,
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              exportSettings: [],
              fills: [{ type: 'SOLID', visible: false, opacity: 1, blendMode: 'NORMAL', color: { r: 1, g: 1, b: 1 } }],
              fillStyleId: '',
              strokes: [],
              strokeStyleId: '',
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              strokeJoin: 'MITER',
              dashPattern: [],
              strokeCap: 'NONE',
              strokeMiterLimit: 4,
              cornerSmoothing: 0,
              topLeftRadius: 8,
              topRightRadius: 8,
              bottomLeftRadius: 8,
              bottomRightRadius: 8,
              paddingLeft: 0,
              paddingRight: 0,
              paddingTop: 0,
              paddingBottom: 0,
              primaryAxisAlignItems: 'MIN',
              counterAxisAlignItems: 'MIN',
              primaryAxisSizingMode: 'AUTO',
              layoutGrids: [],
              gridStyleId: '',
              clipsContent: false,
              constraints: { horizontal: 'MIN', vertical: 'MIN' },
              layoutMode: 'HORIZONTAL',
              counterAxisSizingMode: 'AUTO',
              itemSpacing: 0,
              overflowDirection: 'NONE',
              overlayPositionType: 'CENTER',
              overlayBackground: { type: 'NONE' },
              overlayBackgroundInteraction: 'NONE',
              scaleFactor: 1,
              reactions: [
                {
                  action: {
                    type: 'NODE',
                    destinationId: '1292:159317',
                    navigation: 'CHANGE_TO',
                    transition: { type: 'DISSOLVE', easing: { type: 'LINEAR' }, duration: 0.20000000298023224 },
                    preserveScrollPosition: false,
                  },
                  trigger: { type: 'ON_HOVER' },
                },
              ],
              variantProperties: {
                Size: '2xl',
                Hierarchy: 'Secondary gray',
                Icon: 'Leading',
                Destructive: 'False',
                State: 'Default',
              },
              children: [
                {
                  id: 'I3857:401329;1292:159374',
                  type: 'INSTANCE',
                  name: '_Button base',
                  visible: true,
                  opacity: 1,
                  blendMode: 'PASS_THROUGH',
                  isMask: false,
                  effects: [
                    {
                      type: 'DROP_SHADOW',
                      color: {
                        r: 0.062745101749897,
                        g: 0.0941176488995552,
                        b: 0.1568627506494522,
                        a: 0.05000000074505806,
                      },
                      offset: { x: 0, y: 1 },
                      radius: 2,
                      spread: 0,
                      visible: true,
                      blendMode: 'NORMAL',
                      showShadowBehindNode: true,
                    },
                  ],
                  effectStyleId: 'S:ead01e4696f52ef4db8afb27ee7d9b181dd2016d,',
                  x: 0,
                  y: 0,
                  width: 143,
                  height: 60,
                  rotation: 0,
                  layoutAlign: 'INHERIT',
                  layoutGrow: 0,
                  exportSettings: [],
                  fills: [
                    { type: 'SOLID', visible: true, opacity: 1, blendMode: 'NORMAL', color: { r: 1, g: 1, b: 1 } },
                  ],
                  fillStyleId: 'S:b89f91551fec70712aa14cf0d408f2e9bb40dfec,',
                  strokes: [
                    {
                      type: 'SOLID',
                      visible: true,
                      opacity: 1,
                      blendMode: 'NORMAL',
                      color: { r: 0.8143999576568604, g: 0.8348799347877502, b: 0.8655999898910522 },
                    },
                  ],
                  strokeStyleId: 'S:bfb7ff98d66bd6ff948009949b7ff10486ca3e08,',
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  strokeJoin: 'MITER',
                  dashPattern: [],
                  strokeCap: 'NONE',
                  strokeMiterLimit: 4,
                  cornerSmoothing: 0,
                  topLeftRadius: 8,
                  topRightRadius: 8,
                  bottomLeftRadius: 8,
                  bottomRightRadius: 8,
                  paddingLeft: 28,
                  paddingRight: 28,
                  paddingTop: 16,
                  paddingBottom: 16,
                  primaryAxisAlignItems: 'CENTER',
                  counterAxisAlignItems: 'CENTER',
                  primaryAxisSizingMode: 'AUTO',
                  layoutGrids: [],
                  gridStyleId: '',
                  clipsContent: true,
                  constraints: { horizontal: 'SCALE', vertical: 'SCALE' },
                  layoutMode: 'HORIZONTAL',
                  counterAxisSizingMode: 'AUTO',
                  itemSpacing: 12,
                  overflowDirection: 'NONE',
                  overlayPositionType: 'CENTER',
                  overlayBackground: { type: 'NONE' },
                  overlayBackgroundInteraction: 'NONE',
                  scaleFactor: 1,
                  reactions: [],
                  variantProperties: { Size: '2xl', Icon: 'Leading' },
                  children: [
                    {
                      id: 'I3857:401329;1292:159374;1292:158627',
                      type: 'INSTANCE',
                      name: 'play-circle',
                      visible: true,
                      opacity: 1,
                      blendMode: 'PASS_THROUGH',
                      isMask: false,
                      effects: [],
                      effectStyleId: '',
                      x: 28,
                      y: 18,
                      width: 24,
                      height: 24,
                      rotation: 0,
                      layoutAlign: 'INHERIT',
                      layoutGrow: 0,
                      exportSettings: [],
                      fills: [
                        { type: 'SOLID', visible: false, opacity: 1, blendMode: 'NORMAL', color: { r: 1, g: 1, b: 1 } },
                      ],
                      fillStyleId: '',
                      strokes: [],
                      strokeStyleId: '',
                      strokeWeight: 1,
                      strokeAlign: 'INSIDE',
                      strokeJoin: 'MITER',
                      dashPattern: [],
                      strokeCap: 'NONE',
                      strokeMiterLimit: 4,
                      cornerSmoothing: 0,
                      topLeftRadius: 0,
                      topRightRadius: 0,
                      bottomLeftRadius: 0,
                      bottomRightRadius: 0,
                      paddingLeft: 0,
                      paddingRight: 0,
                      paddingTop: 0,
                      paddingBottom: 0,
                      primaryAxisAlignItems: 'MIN',
                      counterAxisAlignItems: 'MIN',
                      primaryAxisSizingMode: 'AUTO',
                      layoutGrids: [],
                      gridStyleId: '',
                      clipsContent: true,
                      constraints: { horizontal: 'MIN', vertical: 'MIN' },
                      layoutMode: 'NONE',
                      counterAxisSizingMode: 'FIXED',
                      itemSpacing: 0,
                      overflowDirection: 'NONE',
                      overlayPositionType: 'CENTER',
                      overlayBackground: { type: 'NONE' },
                      overlayBackgroundInteraction: 'NONE',
                      scaleFactor: 1,
                      reactions: [],
                      variantProperties: null,
                      children: [
                        {
                          id: 'I3857:401329;1292:159374;1292:158627;1037:34254',
                          type: 'VECTOR',
                          name: 'Icon',
                          visible: true,
                          opacity: 1,
                          blendMode: 'PASS_THROUGH',
                          isMask: false,
                          effects: [],
                          effectStyleId: '',
                          fills: [],
                          fillStyleId: '',
                          strokes: [
                            {
                              type: 'SOLID',
                              visible: true,
                              opacity: 1,
                              blendMode: 'NORMAL',
                              color: { r: 0.20533335208892822, g: 0.2525128722190857, b: 0.328000009059906 },
                            },
                          ],
                          strokeStyleId: 'S:15b99417ed3a906e9e8749339042135cf3725390,',
                          strokeWeight: 2,
                          strokeAlign: 'CENTER',
                          strokeJoin: 'ROUND',
                          dashPattern: [],
                          strokeCap: 'ROUND',
                          strokeMiterLimit: 4,
                          x: 2,
                          y: 2,
                          width: 20,
                          height: 20,
                          rotation: 0,
                          layoutAlign: 'INHERIT',
                          layoutGrow: 0,
                          exportSettings: [],
                          constraints: { horizontal: 'SCALE', vertical: 'SCALE' },
                          cornerSmoothing: 0,
                          handleMirroring: 'NONE',
                          reactions: [],
                          _svg: '<svg width="23" height="22" viewBox="0 0 23 22" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M11.5 21C17.0228 21 21.5 16.5228 21.5 11C21.5 5.47715 17.0228 1 11.5 1C5.97715 1 1.5 5.47715 1.5 11C1.5 16.5228 5.97715 21 11.5 21Z" stroke="#344054" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M9.5 7L15.5 11L9.5 15V7Z" stroke="#344054" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n',
                        },
                      ],
                    },
                    {
                      id: 'I3857:401329;1292:159374;1292:158628',
                      type: 'TEXT',
                      listSpacing: 0,
                      name: 'Text',
                      visible: true,
                      opacity: 1,
                      blendMode: 'PASS_THROUGH',
                      isMask: false,
                      effects: [],
                      effectStyleId: '',
                      strokes: [],
                      strokeStyleId: '',
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      strokeJoin: 'MITER',
                      dashPattern: [],
                      strokeCap: 'NONE',
                      strokeMiterLimit: 4,
                      x: 64,
                      y: 16,
                      width: 51,
                      height: 28,
                      rotation: 0,
                      layoutAlign: 'INHERIT',
                      layoutGrow: 0,
                      exportSettings: [],
                      constraints: { horizontal: 'MIN', vertical: 'MIN' },
                      hasMissingFont: false,
                      paragraphIndent: 0,
                      paragraphSpacing: 18,
                      canUpgradeToNativeBidiSupport: true,
                      autoRename: false,
                      textAlignHorizontal: 'LEFT',
                      textAlignVertical: 'TOP',
                      textAutoResize: 'WIDTH_AND_HEIGHT',
                      reactions: [],
                      _textSegments: [
                        {
                          characters: 'Demo',
                          start: 0,
                          end: 4,
                          fontSize: 18,
                          fontName: { family: 'Inter', style: 'Medium' },
                          textDecoration: 'NONE',
                          textCase: 'ORIGINAL',
                          lineHeight: { unit: 'PIXELS', value: 28 },
                          letterSpacing: { unit: 'PERCENT', value: 0 },
                          fills: [
                            {
                              type: 'SOLID',
                              visible: true,
                              opacity: 1,
                              blendMode: 'NORMAL',
                              color: { r: 0.20533335208892822, g: 0.2525128722190857, b: 0.328000009059906 },
                            },
                          ],
                          textStyleId: 'S:72037c2a0bb676a656d443568b92eda1353998c2,',
                          fillStyleId: 'S:15b99417ed3a906e9e8749339042135cf3725390,',
                          listOptions: { type: 'NONE' },
                          indentation: 0,
                          hyperlink: null,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: '3857:401330',
              type: 'INSTANCE',
              name: 'Button',
              visible: true,
              opacity: 1,
              blendMode: 'PASS_THROUGH',
              isMask: false,
              effects: [],
              effectStyleId: '',
              x: 155,
              y: 0,
              width: 121,
              height: 60,
              rotation: 0,
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              exportSettings: [],
              fills: [{ type: 'SOLID', visible: false, opacity: 1, blendMode: 'NORMAL', color: { r: 1, g: 1, b: 1 } }],
              fillStyleId: '',
              strokes: [],
              strokeStyleId: '',
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              strokeJoin: 'MITER',
              dashPattern: [],
              strokeCap: 'NONE',
              strokeMiterLimit: 4,
              cornerSmoothing: 0,
              topLeftRadius: 8,
              topRightRadius: 8,
              bottomLeftRadius: 8,
              bottomRightRadius: 8,
              paddingLeft: 0,
              paddingRight: 0,
              paddingTop: 0,
              paddingBottom: 0,
              primaryAxisAlignItems: 'MIN',
              counterAxisAlignItems: 'MIN',
              primaryAxisSizingMode: 'AUTO',
              layoutGrids: [],
              gridStyleId: '',
              clipsContent: false,
              constraints: { horizontal: 'MIN', vertical: 'MIN' },
              layoutMode: 'HORIZONTAL',
              counterAxisSizingMode: 'AUTO',
              itemSpacing: 0,
              overflowDirection: 'NONE',
              overlayPositionType: 'CENTER',
              overlayBackground: { type: 'NONE' },
              overlayBackgroundInteraction: 'NONE',
              scaleFactor: 1,
              reactions: [
                {
                  action: {
                    type: 'NODE',
                    destinationId: '1292:158901',
                    navigation: 'CHANGE_TO',
                    transition: { type: 'DISSOLVE', easing: { type: 'LINEAR' }, duration: 0.20000000298023224 },
                    preserveScrollPosition: false,
                  },
                  trigger: { type: 'ON_HOVER' },
                },
              ],
              variantProperties: {
                Size: '2xl',
                Hierarchy: 'Primary',
                Icon: 'False',
                Destructive: 'False',
                State: 'Default',
              },
              children: [
                {
                  id: 'I3857:401330;1292:158922',
                  type: 'INSTANCE',
                  name: '_Button base',
                  visible: true,
                  opacity: 1,
                  blendMode: 'PASS_THROUGH',
                  isMask: false,
                  effects: [
                    {
                      type: 'DROP_SHADOW',
                      color: {
                        r: 0.062745101749897,
                        g: 0.0941176488995552,
                        b: 0.1568627506494522,
                        a: 0.05000000074505806,
                      },
                      offset: { x: 0, y: 1 },
                      radius: 2,
                      spread: 0,
                      visible: true,
                      blendMode: 'NORMAL',
                      showShadowBehindNode: true,
                    },
                  ],
                  effectStyleId: 'S:ead01e4696f52ef4db8afb27ee7d9b181dd2016d,',
                  x: 0,
                  y: 0,
                  width: 121,
                  height: 60,
                  rotation: 0,
                  layoutAlign: 'INHERIT',
                  layoutGrow: 0,
                  exportSettings: [],
                  fills: [
                    {
                      type: 'SOLID',
                      visible: true,
                      opacity: 1,
                      blendMode: 'NORMAL',
                      color: { r: 0.49640899896621704, g: 0.33841174840927124, b: 0.849823534488678 },
                    },
                  ],
                  fillStyleId: 'S:fac2037d87d59fd7517a20a889d522223b8ce9e0,',
                  strokes: [
                    {
                      type: 'SOLID',
                      visible: true,
                      opacity: 1,
                      blendMode: 'NORMAL',
                      color: { r: 0.49640899896621704, g: 0.33841174840927124, b: 0.849823534488678 },
                    },
                  ],
                  strokeStyleId: 'S:fac2037d87d59fd7517a20a889d522223b8ce9e0,',
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  strokeJoin: 'MITER',
                  dashPattern: [],
                  strokeCap: 'NONE',
                  strokeMiterLimit: 4,
                  cornerSmoothing: 0,
                  topLeftRadius: 8,
                  topRightRadius: 8,
                  bottomLeftRadius: 8,
                  bottomRightRadius: 8,
                  paddingLeft: 28,
                  paddingRight: 28,
                  paddingTop: 16,
                  paddingBottom: 16,
                  primaryAxisAlignItems: 'CENTER',
                  counterAxisAlignItems: 'CENTER',
                  primaryAxisSizingMode: 'AUTO',
                  layoutGrids: [],
                  gridStyleId: '',
                  clipsContent: true,
                  constraints: { horizontal: 'SCALE', vertical: 'SCALE' },
                  layoutMode: 'HORIZONTAL',
                  counterAxisSizingMode: 'AUTO',
                  itemSpacing: 8,
                  overflowDirection: 'NONE',
                  overlayPositionType: 'CENTER',
                  overlayBackground: { type: 'NONE' },
                  overlayBackgroundInteraction: 'NONE',
                  scaleFactor: 1,
                  reactions: [],
                  variantProperties: { Size: '2xl', Icon: 'False' },
                  children: [
                    {
                      id: 'I3857:401330;1292:158922;1292:158602',
                      type: 'TEXT',
                      listSpacing: 0,
                      name: 'Text',
                      visible: true,
                      opacity: 1,
                      blendMode: 'PASS_THROUGH',
                      isMask: false,
                      effects: [],
                      effectStyleId: '',
                      strokes: [],
                      strokeStyleId: '',
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      strokeJoin: 'MITER',
                      dashPattern: [],
                      strokeCap: 'NONE',
                      strokeMiterLimit: 4,
                      x: 28,
                      y: 16,
                      width: 65,
                      height: 28,
                      rotation: 0,
                      layoutAlign: 'INHERIT',
                      layoutGrow: 0,
                      exportSettings: [],
                      constraints: { horizontal: 'MIN', vertical: 'MIN' },
                      hasMissingFont: false,
                      paragraphIndent: 0,
                      paragraphSpacing: 18,
                      canUpgradeToNativeBidiSupport: true,
                      autoRename: false,
                      textAlignHorizontal: 'LEFT',
                      textAlignVertical: 'TOP',
                      textAutoResize: 'WIDTH_AND_HEIGHT',
                      reactions: [],
                      _textSegments: [
                        {
                          characters: 'Sign up',
                          start: 0,
                          end: 7,
                          fontSize: 18,
                          fontName: { family: 'Inter', style: 'Medium' },
                          textDecoration: 'NONE',
                          textCase: 'ORIGINAL',
                          lineHeight: { unit: 'PIXELS', value: 28 },
                          letterSpacing: { unit: 'PERCENT', value: 0 },
                          fills: [
                            {
                              type: 'SOLID',
                              visible: true,
                              opacity: 1,
                              blendMode: 'NORMAL',
                              color: { r: 1, g: 1, b: 1 },
                            },
                          ],
                          textStyleId: 'S:72037c2a0bb676a656d443568b92eda1353998c2,',
                          fillStyleId: 'S:b89f91551fec70712aa14cf0d408f2e9bb40dfec,',
                          listOptions: { type: 'NONE' },
                          indentation: 0,
                          hyperlink: null,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: '3857:401315',
              type: 'FRAME',
              name: 'Button - outlined, filled, left, !disabled, primary',
              visible: true,
              opacity: 1,
              blendMode: 'PASS_THROUGH',
              isMask: false,
              effects: [],
              effectStyleId: '',
              x: 288,
              y: 0,
              width: 93,
              height: 36,
              rotation: 0,
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              exportSettings: [],
              fills: [],
              fillStyleId: '',
              strokes: [
                {
                  type: 'SOLID',
                  visible: true,
                  opacity: 0.11999999731779099,
                  blendMode: 'NORMAL',
                  color: { r: 0, g: 0, b: 0 },
                },
              ],
              strokeStyleId: '',
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              strokeJoin: 'MITER',
              dashPattern: [],
              strokeCap: 'NONE',
              strokeMiterLimit: 4,
              cornerSmoothing: 0,
              topLeftRadius: 4,
              topRightRadius: 4,
              bottomLeftRadius: 4,
              bottomRightRadius: 4,
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 6,
              paddingBottom: 6,
              primaryAxisAlignItems: 'CENTER',
              counterAxisAlignItems: 'CENTER',
              primaryAxisSizingMode: 'AUTO',
              layoutGrids: [],
              gridStyleId: '',
              clipsContent: false,
              constraints: { horizontal: 'MIN', vertical: 'MIN' },
              layoutMode: 'HORIZONTAL',
              counterAxisSizingMode: 'AUTO',
              itemSpacing: 4,
              overflowDirection: 'NONE',
              overlayPositionType: 'CENTER',
              overlayBackground: { type: 'NONE' },
              overlayBackgroundInteraction: 'NONE',
              reactions: [],
              children: [
                {
                  id: '3857:401316',
                  type: 'FRAME',
                  name: 'Text',
                  visible: true,
                  opacity: 1,
                  blendMode: 'PASS_THROUGH',
                  isMask: false,
                  effects: [],
                  effectStyleId: '',
                  x: 10,
                  y: 6,
                  width: 73,
                  height: 24,
                  rotation: 0,
                  layoutAlign: 'INHERIT',
                  layoutGrow: 0,
                  exportSettings: [],
                  fills: [],
                  fillStyleId: '',
                  strokes: [],
                  strokeStyleId: '',
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  strokeJoin: 'MITER',
                  dashPattern: [],
                  strokeCap: 'NONE',
                  strokeMiterLimit: 4,
                  cornerSmoothing: 0,
                  topLeftRadius: 0,
                  topRightRadius: 0,
                  bottomLeftRadius: 0,
                  bottomRightRadius: 0,
                  paddingLeft: 6,
                  paddingRight: 6,
                  paddingTop: 4,
                  paddingBottom: 4,
                  primaryAxisAlignItems: 'MIN',
                  counterAxisAlignItems: 'MIN',
                  primaryAxisSizingMode: 'AUTO',
                  layoutGrids: [],
                  gridStyleId: '',
                  clipsContent: false,
                  constraints: { horizontal: 'MIN', vertical: 'MIN' },
                  layoutMode: 'HORIZONTAL',
                  counterAxisSizingMode: 'AUTO',
                  itemSpacing: 0,
                  overflowDirection: 'NONE',
                  overlayPositionType: 'CENTER',
                  overlayBackground: { type: 'NONE' },
                  overlayBackgroundInteraction: 'NONE',
                  reactions: [],
                  children: [
                    {
                      id: '3857:401317',
                      type: 'TEXT',
                      listSpacing: 0,
                      name: 'Label',
                      visible: true,
                      opacity: 1,
                      blendMode: 'PASS_THROUGH',
                      isMask: false,
                      effects: [],
                      effectStyleId: '',
                      strokes: [],
                      strokeStyleId: '',
                      strokeWeight: 0,
                      strokeAlign: 'CENTER',
                      strokeJoin: 'MITER',
                      dashPattern: [],
                      strokeCap: 'NONE',
                      strokeMiterLimit: 4,
                      x: 6,
                      y: 4,
                      width: 61,
                      height: 16,
                      rotation: 0,
                      layoutAlign: 'INHERIT',
                      layoutGrow: 0,
                      exportSettings: [],
                      constraints: { horizontal: 'MIN', vertical: 'CENTER' },
                      hasMissingFont: false,
                      paragraphIndent: 0,
                      paragraphSpacing: 0,
                      canUpgradeToNativeBidiSupport: true,
                      autoRename: false,
                      textAlignHorizontal: 'LEFT',
                      textAlignVertical: 'CENTER',
                      textAutoResize: 'WIDTH_AND_HEIGHT',
                      reactions: [],
                      _textSegments: [
                        {
                          characters: 'Button',
                          start: 0,
                          end: 6,
                          fontSize: 14,
                          fontName: { family: 'Roboto', style: 'Regular' },
                          textDecoration: 'NONE',
                          textCase: 'UPPER',
                          lineHeight: { unit: 'PIXELS', value: 16 },
                          letterSpacing: { unit: 'PIXELS', value: 1.25 },
                          fills: [
                            {
                              type: 'SOLID',
                              visible: true,
                              opacity: 1,
                              blendMode: 'NORMAL',
                              color: { r: 0.3843137323856354, g: 0, b: 0.9333333373069763 },
                            },
                          ],
                          textStyleId: '',
                          fillStyleId: '',
                          listOptions: { type: 'NONE' },
                          indentation: 0,
                          hyperlink: null,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
} as unknown as SceneNodeNoMethod;
