FROM hasura/graphql-engine:v2.9.0
# No customization. This dockerfile is to allow easy deployments on google cloud.
# The repo is watched and, on change on this Dockerfile, it builds it and stores in the
# Google image repository.
# To upgrade to a more recent Hasura verison, just change the version here and push.
