FROM hasura/graphql-engine:v2.10.1
# No customization. This dockerfile is to allow easy deployments on google cloud.
# The repo is watched and, on change on this Dockerfile, it builds it and stores in the
# Google image repository.
# See db/README.md to update the version number.
